FEATURE_FLAGS = {
    'EMBEDDED_SUPERSET': True,
    'DASHBOARD_RBAC': False,
}
WTF_CSRF_ENABLED = True
TALISMAN_ENABLED = False
HTTP_HEADERS = {'X-Frame-Options': 'ALLOWALL'}
GUEST_TOKEN_JWT_AUDIENCE = 'http://localhost:8088/'
GUEST_TOKEN_JWT_EXP_SECONDS = 300
CONTENT_SECURITY_POLICY_WARNING = False
