import { NextRequest } from 'next/server'
import { getDb } from '@/lib/db'
import { getSession } from '@/lib/auth'
import { renderHtmlToPdf, htmlShell } from '@/lib/pdf-renderer'
export const runtime = 'nodejs'

export async function POST(req: NextRequest) {
  const session = await getSession()
  if (!session || session.role !== 'admin') {
    return Response.json({ error: 'Admin required' }, { status: 403 })
  }

  const { template_id } = await req.json()
  if (!template_id) return Response.json({ error: 'template_id required' }, { status: 400 })

  const sql = getDb()
  const [template] = await sql`SELECT * FROM report_templates WHERE id = ${template_id}`
  if (!template) return Response.json({ error: 'Template not found' }, { status: 404 })

  const t = template as Record<string, unknown>
  const name = String(t.name)
  const type = String(t.type || 'operational')
  const description = String(t.description || '')

  try {
    // Build a simple operational report HTML
    const now = new Date()
    const body = `
      <div class="section">
        <div class="section-title">Report Overview</div>
        <div class="insight">${description || 'Scheduled operational report generated by Mosaic.'}</div>
        <div class="kpi-grid">
          <div class="kpi">
            <div class="kpi-label">Generated</div>
            <div class="kpi-value" style="font-size:14px">${now.toLocaleDateString('en-GB', { day:'numeric', month:'long', year:'numeric' })}</div>
          </div>
          <div class="kpi">
            <div class="kpi-label">Report Type</div>
            <div class="kpi-value" style="font-size:14px;text-transform:capitalize">${type}</div>
          </div>
          <div class="kpi">
            <div class="kpi-label">Trigger</div>
            <div class="kpi-value" style="font-size:14px">Manual</div>
          </div>
        </div>
      </div>
      <div class="section">
        <div class="section-title">Template Configuration</div>
        <table>
          <tbody>
            <tr><td style="font-weight:600;width:140px">Template name</td><td>${name}</td></tr>
            <tr><td style="font-weight:600">Type</td><td style="text-transform:capitalize">${type}</td></tr>
            ${t.schedule ? `<tr><td style="font-weight:600">Schedule</td><td>${t.schedule}</td></tr>` : ''}
            ${t.recipients ? `<tr><td style="font-weight:600">Recipients</td><td>${(()=>{ try { return JSON.parse(String(t.recipients)).join(', ') || '—' } catch { return String(t.recipients) || '—' } })()}</td></tr>` : ''}
          </tbody>
        </table>
      </div>
      <div class="section">
        <div class="section-title">Note</div>
        <div class="insight">This is a template test run. To include live data sections, configure data bindings in the template builder (coming soon). This report confirms the template is correctly set up and PDF generation is working.</div>
      </div>
    `

    const html = htmlShell(name, body, `${type.charAt(0).toUpperCase() + type.slice(1)} Report · ${now.toLocaleDateString('en-GB', { day:'numeric', month:'long', year:'numeric' })}`)
    const pdfBuffer = await renderHtmlToPdf(html)

    // Record in report_instances
    const [instance] = await sql`
      INSERT INTO report_instances (name, type, trigger, template_id, triggered_by, status, pdf_size, generated_at)
      VALUES (${name}, ${type}, 'manual', ${template_id}, ${session.id}, 'completed', ${pdfBuffer.length}, datetime('now'))
      RETURNING *`

    return Response.json({
      ok: true,
      instance_id: (instance as Record<string,unknown>).id,
      pdf_size: pdfBuffer.length,
      message: `Report "${name}" generated successfully`,
    })
  } catch (e) {
    console.error('Report generation error:', e)
    // Record failure
    await sql`
      INSERT INTO report_instances (name, type, trigger, template_id, triggered_by, status, error, generated_at)
      VALUES (${name}, ${type}, 'manual', ${template_id}, ${session.id}, 'failed', ${(e as Error).message}, datetime('now'))
    `.catch(() => {})
    return Response.json({ error: (e as Error).message }, { status: 500 })
  }
}
