// install.js — Mosaic installer core logic
//
// Deploys Mosaic via Docker Compose against prebuilt GHCR images (pull-based, no
// on-device build). The edition choice maps to compose profiles:
//   Personal   → no profiles (core services only)
//   Enterprise → --profile bundled --profile metering (+ optional ciso)
//
// Deliberately minimal config at install time: edition + admin account. Mosaic is
// served by Caddy at https://localhost. The Anthropic API key is NOT collected here — Mosaic runs without AI (workflows,
// rules, notifications, dashboards) and the key is added later in Settings. No
// nvm / Node / native service management: Docker owns the runtime and restart
// policies own persistence.

const { spawn, execSync } = require('child_process')
const fs = require('fs')
const path = require('path')
const os = require('os')
const crypto = require('crypto')
const http = require('http')
const https = require('https')

const HOME = os.homedir()

// Docker Desktop installs docker on PATHs that a GUI-launched app may not inherit.
const EXTENDED_PATH = [
  '/usr/local/bin', '/opt/homebrew/bin', '/usr/bin', '/bin',
  '/Applications/Docker.app/Contents/Resources/bin',
].join(':')

function dockerEnv() {
  return { ...process.env, PATH: EXTENDED_PATH + ':' + (process.env.PATH || '') }
}

// ── Shell helpers ─────────────────────────────────────────────────────────────
function run(cmd, cwd, onData) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, { shell: true, cwd, env: dockerEnv() })
    let stderr = ''
    child.stdout.on('data', d => onData && onData(d.toString()))
    child.stderr.on('data', d => { stderr += d.toString(); onData && onData(d.toString()) })
    child.on('close', code => code === 0 ? resolve() : reject(new Error(stderr.trim() || `Command failed: ${cmd}`)))
    child.on('error', reject)
  })
}

function execSafe(cmd) {
  try { return execSync(cmd, { env: dockerEnv(), stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim() }
  catch { return null }
}

function randomHex(n) { return crypto.randomBytes(n).toString('hex') }

// ── Edition → compose profiles ────────────────────────────────────────────────
// The single lever that distinguishes editions. Personal runs the untagged core;
// Enterprise adds the bundled heavyweight services and the metering stack.
function profileArgs(edition) {
  if (edition === 'enterprise') return '--profile bundled --profile metering'
  return '' // personal: core only
}

// ── Write the .env Compose reads ──────────────────────────────────────────────
// Only what's needed to boot. AUTH_SECRET is the one truly-mandatory secret
// (session signing); it's generated here so the user never has to. CRON_SECRET
// secures the in-app scheduler's loopback self-call. No Anthropic key.
function writeEnv(installDir, config) {
  const lines = [
    '# Generated by the Mosaic installer — do not commit.',
    `MOSAIC_EDITION=${config.edition || 'personal'}`,
    `MOSAIC_VERSION=${config.version || 'latest'}`,
    '',
    '# Canonical SQLite DB filename (Personal default). For Postgres, set',
    '# DATABASE_URL=postgres://… and this is ignored.',
    'MOSAIC_DB_FILE=mosaic.db',
    '',
    '# Mosaic is served by Caddy at https://localhost (ports 443/80, fixed in the',
    '# compose). To use a real hostname + Let\'s Encrypt cert, set MOSAIC_HOSTNAME',
    '# to a public DNS name and give Caddy an ACME email (see docker-compose.yml).',
    '',
    '# Auto-generated secrets — the only ones required before first boot.',
    `AUTH_SECRET=${randomHex(24)}`,
    `CRON_SECRET=${randomHex(16)}`,
    '',
    '# Anthropic key is intentionally blank — Mosaic runs without AI. Add it later',
    '# in Settings → API keys to enable chat / RCA.',
    'ANTHROPIC_API_KEY=',
    '',
    '# Superset (Enterprise bundled) requires a secret key even when unused, since',
    '# compose validates all service definitions. Generated so Enterprise installs',
    '# succeed; harmless for Personal (the superset service never starts).',
    `SUPERSET_SECRET_KEY=${randomHex(32)}`,
    '',
    '# Initial admin — Mosaic provisions this account on first boot, then the',
    '# user is prompted to change the password. No Anthropic key here: add it',
    '# later in Settings → API keys (Mosaic runs without AI until then).',
    `ADMIN_EMAIL=${config.adminEmail || ''}`,
    `ADMIN_NAME=${config.adminName || 'Administrator'}`,
    `ADMIN_PASSWORD=${config.adminPassword || ''}`,
    '',
  ]
  // OPENMETER_URL is only meaningful for Enterprise (metering profile). Omit it
  // for Personal so the app doesn't attempt doomed metering calls to a host that
  // isn't running (metering is fire-and-forget, but omitting is cleaner).
  if (config.edition === 'enterprise') {
    lines.push('OPENMETER_URL=http://openmeter:8888', '')
  }
  fs.writeFileSync(path.join(installDir, '.env'), lines.join('\n') + '\n', { mode: 0o600 })
}

// ── Wait for the app to answer ────────────────────────────────────────────────
function waitForServer(url, timeoutSec) {
  const deadline = Date.now() + timeoutSec * 1000
  return new Promise((resolve) => {
    const tick = () => {
      const lib = url.startsWith('https') ? https : http
      const req = lib.get(url, { rejectUnauthorized: false }, res => { res.resume(); resolve(true) })
      req.on('error', () => { Date.now() > deadline ? resolve(false) : setTimeout(tick, 3000) })
      req.setTimeout(4000, () => { req.destroy(); Date.now() > deadline ? resolve(false) : setTimeout(tick, 3000) })
    }
    tick()
  })
}

// ── The install flow ──────────────────────────────────────────────────────────
async function install(config, rawEmit) {
  const emit = (d) => { try { rawEmit && rawEmit(d) } catch {} }
  const TOTAL = 6
  try {
    const installDir = config.installDir || path.join(HOME, 'Mosaic')
    const edition = config.edition === 'enterprise' ? 'enterprise' : 'personal'
    const profiles = profileArgs(edition)

    // 1 — directories
    emit({ step: 1, total: TOTAL, pct: 6, label: 'Preparing installation folder…' })
    fs.mkdirSync(installDir, { recursive: true })
    fs.mkdirSync(path.join(installDir, 'backups'), { recursive: true })

    // 2 — stage the compose file + supporting assets (shipped in the app bundle)
    emit({ step: 2, total: TOTAL, pct: 14, label: 'Staging deployment files…' })
    const bundledCompose = path.join(config.resourcesDir || __dirname, 'deploy', 'docker-compose.yml')
    const destCompose = path.join(installDir, 'docker-compose.yml')
    if (fs.existsSync(bundledCompose)) {
      fs.copyFileSync(bundledCompose, destCompose)
    } else if (!fs.existsSync(destCompose)) {
      throw new Error('Bundled docker-compose.yml not found in installer resources.')
    }
    // Copy every bundled deploy asset into the install folder, recursively. The
    // compose bind-mounts host-path files (docker/caddy/Caddyfile, the openmeter/
    // ciso/superset configs, NETWORK.md), so the whole tree must be present or the
    // containers fail to start (Docker creates an empty dir where a file is
    // expected). fs.cpSync (Node 16.7+) handles nested dirs.
    const deployDir = path.join(config.resourcesDir || __dirname, 'deploy')
    if (fs.existsSync(deployDir)) {
      for (const f of fs.readdirSync(deployDir)) {
        if (f === 'docker-compose.yml') continue // already placed above
        if (f === '.gitignore' || f === '.gitkeep') continue
        const src = path.join(deployDir, f)
        const dest = path.join(installDir, f)
        fs.cpSync(src, dest, { recursive: true })
      }
    }

    // 3 — configuration
    emit({ step: 3, total: TOTAL, pct: 22, label: 'Writing configuration…' })
    writeEnv(installDir, { ...config, edition })

    // 4 — Docker preflight (must be installed AND running)
    emit({ step: 4, total: TOTAL, pct: 30, label: 'Checking Docker…' })
    const dockerVersion = execSafe('docker --version')
    if (!dockerVersion) throw new Error('Docker is not installed. Install Docker Desktop, then run this installer again.')
    const dockerInfo = execSafe('docker info')
    if (!dockerInfo) throw new Error('Docker is installed but not running. Start Docker Desktop, wait for it to finish starting, then run this installer again.')

    // 5 — pull images + start the stack
    emit({ step: 5, total: TOTAL, pct: 38,
      label: edition === 'enterprise'
        ? 'Pulling Enterprise images (first run downloads several GB)…'
        : 'Pulling Mosaic images (first run may take a few minutes)…' })

    // Pull the published images, then start. This installer ships only the
    // compose file (not the source tree), so it is strictly pull-based — there is
    // no local-build fallback. If the pull fails, surface a clear, honest error
    // rather than attempting a build that can't succeed.
    try {
      await run(`docker compose ${profiles} pull`, installDir, d => {
        emit({ step: 5, total: TOTAL, pct: 55, label: `Downloading: ${d.trim().slice(0, 58)}` })
      })
    } catch (e) {
      throw new Error(
        'Could not download the Mosaic images from the registry. This usually means ' +
        'the release images are not published or not public yet, or there is no internet ' +
        'connection. Check your connection and try again; if it persists, the images for ' +
        'this version may not be available. (' + (e.message || 'pull failed').slice(0, 120) + ')'
      )
    }

    emit({ step: 5, total: TOTAL, pct: 70, label: 'Starting Mosaic services…' })
    await run(`docker compose ${profiles} up -d`, installDir, d => {
      emit({ step: 5, total: TOTAL, pct: 80, label: `Starting: ${d.trim().slice(0, 58)}` })
    })

    // 6 — wait for readiness
    // Mosaic's entry point is Caddy on https://localhost (443) — the reverse proxy
    // in front of the app. Caddy uses its internal CA for localhost, so the cert is
    // self-signed (waitForServer ignores cert validation). The app container itself
    // listens on 3001 internally; Caddy is the front door users open.
    emit({ step: 6, total: TOTAL, pct: 88, label: 'Waiting for Mosaic to be ready…' })
    const appUrl = 'https://localhost'
    const ready = await waitForServer('https://localhost/login', 180)

    emit({
      step: 6, total: TOTAL, pct: 100,
      label: ready ? 'Installation complete!' : 'Services started — finishing warm-up…',
      done: true,
      appUrl,
      edition,
      ready,
    })
    return { ok: true, appUrl, edition, ready }
  } catch (err) {
    emit({ error: true, message: err.message || String(err) })
    return { ok: false, error: err.message || String(err) }
  }
}

// ── Preflight requirement checks (shown before install) ───────────────────────
async function checkRequirements(config) {
  const results = []

  // Docker installed
  const dockerVersion = execSafe('docker --version')
  results.push({
    name: 'Docker',
    ok: !!dockerVersion,
    detail: dockerVersion ? dockerVersion : 'Not found — install Docker Desktop (required)',
  })

  // Docker running
  if (dockerVersion) {
    const running = !!execSafe('docker info')
    results.push({
      name: 'Docker running',
      ok: running,
      detail: running ? 'Docker Desktop is running' : 'Docker is installed but not running — start Docker Desktop',
    })
    // RAM allotted to Docker (Enterprise wants more)
    const memBytes = Number(execSafe(`docker info --format '{{.MemTotal}}'`))
    if (memBytes) {
      const memGB = Math.round(memBytes / 1024 / 1024 / 1024)
      const wantGB = (config && config.edition === 'enterprise') ? 8 : 4
      results.push({
        name: 'Docker memory',
        ok: memGB >= wantGB,
        detail: memGB >= wantGB
          ? `${memGB} GB allotted`
          : `${memGB} GB — recommend ${wantGB} GB+ (Docker → Settings → Resources)`,
      })
    }
  }

  // Disk space
  try {
    const out = execSync(`df -g "${HOME}"`).toString()
    const m = out.match(/\s+(\d+)\s+\d+%/)
    const freeGB = m ? parseInt(m[1]) : 20
    const wantGB = (config && config.edition === 'enterprise') ? 15 : 5
    results.push({ name: 'Disk space', ok: freeGB >= wantGB, detail: `${freeGB} GB free (need ${wantGB} GB+)` })
  } catch {
    results.push({ name: 'Disk space', ok: true, detail: 'Could not check — assuming OK' })
  }

  // Port availability. Mosaic is served by Caddy on 443 (https) and 80 (http
  // redirect) — these are fixed in the compose, so we check those, not a
  // user-chosen port. 443 is the one that matters (the app's front door).
  const checkPort = (p) => new Promise((resolve) => {
    const net = require('net')
    const srv = net.createServer()
    srv.once('error', () => resolve(false))
    srv.once('listening', () => { srv.close(); resolve(true) })
    srv.listen(p, '127.0.0.1')
  })
  const p443 = await checkPort(443)
  results.push({
    name: 'Port 443',
    ok: p443,
    detail: p443 ? 'Available (https)' : 'In use — stop whatever is using 443 (another web server?)',
  })

  // Internet (needed to pull images)
  const online = await new Promise((resolve) => {
    const req = https.get('https://ghcr.io', res => { res.resume(); resolve(true) })
    req.on('error', () => resolve(false))
    req.setTimeout(5000, () => { req.destroy(); resolve(false) })
  })
  results.push({
    name: 'Internet',
    ok: online,
    detail: online ? 'Connected (can reach GHCR)' : 'Offline — needed to download Mosaic images',
  })

  return results
}

module.exports = { install, checkRequirements }
